[project]
name = "streamlit-yandex-stt"
version = "0.0.1"
description = "Yandex speech to text showcase"
requires-python = ">=3.13"
dependencies = [
    "streamlit==1.52.2",
    "yandex-speechkit",
    "python-dotenv",
    "audioop-lts",
]
